version: '3.8'

services:
  # Servizio MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: FootBRO
      # RIMUOVI queste due righe - causano l'errore:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  # Servizio Spring Boot
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/FootBRO
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
    networks:
      - app-network
    restart: unless-stopped

# Volumi persistenti
volumes:
  mysql-data:

# Rete personalizzata
networks:
  app-network:
    driver: bridge